'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const crypto=require('node:crypto'); const fs=require('node:fs'); const path=require('node:path'); const sharp=require('sharp'); const packageJson=require('../package.json');
const {POSTS,buildContentHtml,htmlToText}=require('../src/scripts/seed-adsense-blog-posts'); const {getArticleModule,listArticleSlugs}=require('../src/content/adsense-blog-article-registry'); const {getInitialIndexingClassification}=require('../src/content/adsense-content-indexing'); const {evaluateBlogContentEligibility,hasCurrentPublicationReview}=require('../src/utils/blog-content-eligibility'); const {buildCreatePayload,getCanonicalSeed,parseArguments}=require('../src/scripts/create-adsense-blog');
const {ARTICLE,CANONICAL_SLUG,RAW_CONTENT_HTML,REQUIRED_HEADINGS,REQUIRED_LINKS,buildArticlePayload,validateArticlePayload}=require('../src/content/increase-running-distance');
const COVER='/images/blog/covers/how-to-increase-running-distance.webp'; const COVER_PATH=path.join(__dirname,'..','src','public','images','blog','covers','how-to-increase-running-distance.webp'); const PUBLISH_AT='2026-10-03T11:00:00.000Z';

test('distance progression guide builds the approved substantive payload',()=>{const p=buildArticlePayload({coverImageUrl:COVER}); const words=p.contentText.split(/\s+/).filter(Boolean).length; assert.equal(p.title,'How to Increase Running Distance Without Adding Too Much Too Soon'); assert.equal(p.seoDescription,'Learn practical ways to increase running distance gradually by adjusting one part of your routine at a time, using easy effort, recovery, and realistic weekly planning.'); assert.equal(p.tags[1],'increase running distance'); assert.ok(words>=2500&&words<=3000); assert.equal(p.readingTime,Math.ceil(words/180)); assert.equal(p.contentRaw,p.contentText); assert.doesNotThrow(()=>validateArticlePayload(p)); assert.doesNotMatch(p.contentHtml,/<h1\b/i); for(const h of REQUIRED_HEADINGS) assert.ok(p.contentHtml.includes(`<h2>${h}</h2>`)); for(const l of REQUIRED_LINKS) assert.ok(p.contentHtml.includes(l));});
test('guide covers baseline, one-variable changes, easy effort, recovery, missed distance, conditions, and progression',()=>{const {contentText:t}=buildArticlePayload({coverImageUrl:COVER}); for(const pattern of [/ordinary recent weeks/i,/change one part of the routine at a time/i,/10 percent rule is a heuristic/i,/Walking is a legitimate/i,/A missed run is not distance debt/i,/DOST-PAGASA/i,/Moving from 5K toward 10K/i,/Moving from 10K toward 21K/i]) assert.match(t,pattern);});
test('official sources sanitize and health eligibility passes',()=>{const p=buildArticlePayload({coverImageUrl:COVER}); const e=evaluateBlogContentEligibility({...p,contentRisk:'health_safety',coverImageUrl:COVER},{evaluatedAt:new Date('2026-09-13T00:00:00Z')}); assert.notEqual(p.contentHtml,RAW_CONTENT_HTML.trim()); assert.match(p.contentHtml,/health\.gov\/paguidelines\/second-edition\/pdf\/Physical_Activity_Guidelines_2nd_edition\.pdf" rel="noopener noreferrer" target="_blank"/); assert.match(p.contentHtml,/cdc\.gov\/healthy-weight-growth\/physical-activity\/getting-started\.html" rel="noopener noreferrer" target="_blank"/); assert.match(p.contentHtml,/nhs\.uk\/better-health\/get-active\/get-running-with-couch-to-5k\/couch-to-5k-running-plan\/" rel="noopener noreferrer" target="_blank"/); assert.equal(e.eligible,true); assert.equal(e.healthReviewRequired,true); assert.deepEqual(e.blockingReasons,[]); assert.equal(e.externalLinkCount,4);});
test('guide has a distinct 1600 by 900 WebP cover',async()=>{const m=await sharp(COVER_PATH).metadata(); assert.deepEqual([m.format,m.width,m.height],['webp',1600,900]); const hash=crypto.createHash('sha256').update(fs.readFileSync(COVER_PATH)).digest('hex'); const duplicates=fs.readdirSync(path.dirname(COVER_PATH)).filter(n=>n.endsWith('.webp')&&n!==path.basename(COVER_PATH)&&crypto.createHash('sha256').update(fs.readFileSync(path.join(path.dirname(COVER_PATH),n))).digest('hex')===hash); assert.deepEqual(duplicates,[]);});
test('guide is registered and seeded once for October 3',()=>{const matches=POSTS.filter(p=>p.slug===CANONICAL_SLUG),seed=matches[0]; assert.equal(getArticleModule(CANONICAL_SLUG).ARTICLE,ARTICLE); assert.equal(listArticleSlugs().length,54); assert.equal(POSTS.length,54); assert.equal(matches.length,1); assert.equal(getCanonicalSeed(CANONICAL_SLUG),seed); assert.equal(buildContentHtml(seed),seed.contentHtml); assert.equal(htmlToText(seed.contentHtml),buildArticlePayload({coverImageUrl:COVER}).contentText); assert.equal(seed.status,'scheduled'); assert.equal(seed.publishedAt,PUBLISH_AT);});
test('guide links to Topic 1 but omits later unpublished October topics',()=>{const p=buildArticlePayload({coverImageUrl:COVER}); assert.match(p.contentHtml,/href="\/blog\/what-is-a-long-run-for-beginners"/); for(const slug of ['what-is-an-easy-run','strength-training-for-runners','how-to-prepare-for-a-long-run']) assert.equal(p.contentHtml.includes(`/blog/${slug}`),false);});
test('creator schedules one reviewed noindex health record',()=>{assert.deepEqual(parseArguments(['--slug',CANONICAL_SLUG,'--apply','--confirm-editorial-review','--publish-at',PUBLISH_AT]),{slug:CANONICAL_SLUG,mode:'apply',confirmEditorialReview:true,publishAt:PUBLISH_AT}); assert.deepEqual(getInitialIndexingClassification(CANONICAL_SLUG),{contentRisk:'health_safety',indexCandidate:false,plannedNoindex:true}); const p=buildCreatePayload({slug:CANONICAL_SLUG,authorId:'507f1f77bcf86cd799439011',now:new Date('2026-09-13T01:00:00Z'),publishAt:new Date(PUBLISH_AT),confirmEditorialReview:true}); assert.equal(p.status,'scheduled'); assert.equal(p.searchIndexingStatus,'noindex'); assert.equal(p.searchIndexingReason,'pending_expert_review'); assert.equal(hasCurrentPublicationReview(p),true); assert.match(packageJson.scripts['blog:update-increase-running-distance'],new RegExp(CANONICAL_SLUG));});
test('validator rejects unsafe progression and event claims',()=>{const p=buildArticlePayload({coverImageUrl:COVER}); const claim=c=>({...p,contentText:`${p.contentText} ${c}`,contentRaw:`${p.contentText} ${c}`}); assert.throws(()=>validateArticlePayload(claim('The 10 percent always guarantees safety.')),/10 percent/); assert.throws(()=>validateArticlePayload(claim('You should double the next run.')),/catch-up/); assert.throws(()=>validateArticlePayload(claim('Every runner must add 5 kilometres.')),/universal increase/); assert.throws(()=>validateArticlePayload(claim('Everyone needs the same gel.')),/fueling/); assert.throws(()=>validateArticlePayload(claim('Every event accepts walking.')),/event rules/); assert.throws(()=>buildArticlePayload(),/cover artwork/);});
