'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');const ejs=require('ejs');
const ROOT=path.resolve(__dirname,'..');const viewPath=path.join(ROOT,'src/views/pages/policy.ejs');const view=fs.readFileSync(viewPath,'utf8');const css=fs.readFileSync(path.join(ROOT,'src/public/css/terms-page.css'),'utf8');
const {buildPublicPolicyPresentation,normalizePolicyHtml,formatPolicyDate}=require('../src/services/public-policy-presentation.service');
const {nextVersion,prepareTermsDraft}=require('../src/services/terms-draft.service');
const {buildTermsNotice,processTermsNoticeBatch}=require('../src/services/policy-notice.service');
const {buildNotificationPresentation}=require('../src/services/notification.service');

test('legacy Terms headings become one-page hierarchy with stable contents',()=>{const legacy='<h1>HelloRun Terms and Conditions</h1><p><strong>Last Updated:</strong> 9 March 2026</p><h1>1. Agreement</h1><p>Text</p><h1>2. Agreement</h1><h2>Details</h2>';const normalized=normalizePolicyHtml(legacy,{title:'Terms and Conditions',dbTitle:'HelloRun Terms and Conditions'});assert.doesNotMatch(normalized.html,/HelloRun Terms and Conditions|Last Updated/);assert.equal((normalized.html.match(/<h1/g)||[]).length,0);assert.equal((normalized.html.match(/<h2/g)||[]).length,3);assert.deepEqual(normalized.contents.map(x=>x.id),['1-agreement','2-agreement','details']);});
test('normalization removes empty leading markup and collision-proofs hostile heading labels',()=>{const normalized=normalizePolicyHtml('<h1>HelloRun Terms and Conditions</h1><p><br /></p><h1>&lt;script&gt;Rules&lt;/script&gt;</h1><h2>&lt;script&gt;Rules&lt;/script&gt;</h2>',{dbTitle:'HelloRun Terms and Conditions'});assert.match(normalized.html,/^<h2/);assert.doesNotMatch(normalized.html,/^<p><br/);assert.deepEqual(normalized.contents.map(x=>x.id),['rules','rules-2']);});
test('presentation formats unambiguous dates and Terms metadata',()=>{const p=buildPublicPolicyPresentation({policyDocument:{key:'terms',title:'Terms and Conditions'},policyHtml:'<h1>Terms and Conditions</h1><h1>Rules</h1><p>one two three</p>',policyMeta:{versionNumber:'1.2',effectiveDate:'2026-03-09T00:00:00Z',updatedAt:'2026-07-19T00:00:00Z',summaryOfChanges:'Clearer rules.'}});assert.equal(p.versionLabel,'Version 1.2');assert.equal(p.effectiveLabel,'9 March 2026');assert.equal(formatPolicyDate('bad'),'');assert.equal(p.contents[0].label,'Rules');assert.equal(p.summary.length,6);});
test('Terms template is content-first, server-navigable, printable, and modal/ad free',()=>{assert.doesNotThrow(()=>ejs.compile(view,{filename:viewPath}));assert.equal((view.match(/<h1\b/g)||[]).length,2,'mutually exclusive Terms and generic policy branches each own one h1');for(const marker of ['Terms at a glance','terms-mobile-contents','terms-contents','pending-organizer-terms','Print Terms','Related policies and help'])assert.match(view,new RegExp(marker));assert.doesNotMatch(view,/ad-unit|run-proof-modal-dialog/i);assert.match(css,/max-width:70ch/);assert.match(css,/@media print/);assert.match(css,/min-height:44px/);assert.match(css,/:focus-visible/);});
test('review source uses selected identity and current workflows without unsupported providers',()=>{const source=fs.readFileSync(path.join(ROOT,'docs/policy-markdown-pack/terms-and-conditions.md'),'utf8');assert.match(source,/Henson M\. Sagorsor, operating as 4HProjects/);for(const phrase of ['accumulated','Pending accumulated distance','exceed the selected goal','finalized only after','public revision history','Republic of the Philippines'])assert.match(source,new RegExp(phrase,'i'));assert.doesNotMatch(source,/4HProjects Inc|Stripe|PayMongo|Xendit|guarantee AdSense approval/i);});
test('draft preparation chooses next version and is idempotent',async()=>{assert.equal(nextVersion(['1.0','1.1','bad']),'1.2');const source='# Terms\n\n## Rules\n\nUse them.';let created=0;const existing={_id:'draft',versionNumber:'1.2',contentMarkdown:source};const Model={findOne:()=>({lean:async()=>created?existing:null}),find:()=>({select:()=>({lean:async()=>[{versionNumber:'1.1'}]})}),create:async(payload)=>{created++;return{...payload,toObject(){return payload;}}}};const first=await prepareTermsDraft({Model,contentMarkdown:source});const second=await prepareTermsDraft({Model,contentMarkdown:source});assert.equal(first.created,true);assert.equal(first.policy.status,'draft');assert.equal(first.policy.isCurrent,false);assert.equal(second.created,false);});
test('Terms notices are deduplicated, runner-safe, and non-blocking',()=>{const notice=buildTermsNotice({_id:'policy123',versionNumber:'1.2',summaryOfChanges:'Clearer event responsibilities.'});assert.equal(notice.dedupeKey,'terms-policy:policy123');assert.equal(notice.href,'/terms#terms-changes');const presentation=buildNotificationPresentation(notice);assert.equal(presentation.category,'Account and policy');assert.equal(presentation.actionLabel,'Review terms');});
test('notice batches exclude closed accounts and use retry-safe upserts',async()=>{let userQuery;let operations;const userId={toString:()=> 'user1'};const policy={_id:'policy123',versionNumber:'1.2',summaryOfChanges:'Summary',publishedAt:new Date('2026-07-19'),noticeDispatch:{audienceBeforeAt:new Date('2026-07-19'),lastUserId:null}};const Policy={findOneAndUpdate:()=>({lean:async()=>policy}),updateOne:async()=>({})};const Users={find:(query)=>{userQuery=query;return{select:()=>({sort:()=>({limit:()=>({lean:async()=>[{_id:userId}]})})})}}};const Notifications={bulkWrite:async(ops)=>{operations=ops;}};const result=await processTermsNoticeBatch({Policy,Users,Notifications,now:new Date('2026-07-20')});assert.equal(result.processed,1);assert.deepEqual(userQuery.accountStatus,{$ne:'closed'});assert.equal(operations[0].updateOne.upsert,true);assert.equal(operations[0].updateOne.filter.dedupeKey,'terms-policy:policy123');});
